name: 'Build branch'

on:
  push:
    branches-ignore:
      - "master"
jobs:
  build-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PRISMIC_CUSTOM_TYPES_API_TOKEN: ${{ secrets.PRISMIC_CUSTOM_TYPES_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install canvas dependencies
        run: sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev

      - name: Install dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Build
        run: yarn build
